# main text of home
name: Maria Isabelli
bio: print('Hello World'), Full Stack Developer, specialized in systems analysis and development and DevSecOps.

# site settings
url: "https://mariaisabelli.github.io"
baseurl: ""  # mantenha vazio se estiver usando o repositório MariaIsabelli.github.io

# if it's an external image, update below for true
# better with square images
external-image: false
picture: /assets/images/perfil.jpg  # com / no começo para evitar erro de caminho

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# social media links (só descomentar o que você usa)
instagram: https://www.instagram.com/marie.isabelli/
linkedin: https://www.linkedin.com/in/maria-isabelli-365543215/
github: https://github.com/MariaIsabelli
medium: https://medium.com/@mariaisabellipinto
email: mariaisabellipinto@gmail.com

# site layout options
width: normal  # opções: normal (560px) ou large (810px)

# pagination
pagination:
  enabled: false
  sort_reverse: true
  title: ":title"
  per_page: 5
  permalink: "/:num/"

# resume settings
resume-external: true
resume-url: https://docs.google.com/document/d/1LUMWTgDC4VX8JvDfLBahBpceGzik41ArqaYBevEN9Qo/edit?usp=drive_link

# enable animations
animation: true

# enable plugins
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

# arquivos a serem ignorados no build
exclude:
  - travis.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - node_modules
  - vendor
